import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    backgroundColor: '#f8fafc',
  },
  listContent: {
    paddingBottom: 28,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  loadingText: {
    marginTop: 14,
    color: '#64748b',
    fontSize: 15,
  },
  heroSection: {
    backgroundColor: '#e0ecff',
    borderRadius: 20,
    padding: 14,
    marginBottom: 12,
  },
  heroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 10,
  },
  heroBadgeText: {
    color: '#1d4ed8',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 4,
  },
  heroSubtitle: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  searchWrapper: {
    marginTop: 12,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 12,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchIcon: {
    marginRight: 6,
  },
  searchInput: {
    flex: 1,
    color: '#0f172a',
    fontSize: 14,
    paddingVertical: 10,
  },
  clearSearchButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
  },
  filterButton: {
    marginTop: 12,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
  filterChevron: {
    marginLeft: 'auto',
  },
  filterButtonText: {
    color: '#2563eb',
    fontSize: 13,
    fontWeight: '700',
  },
  filterBadge: {
    backgroundColor: '#ef4444',
    borderRadius: 999,
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  filtersPanelCompact: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#e0e7ff',
    paddingVertical: 10,
  },
  filterCompactRow: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterCompactSection: {
    gap: 6,
  },
  filterCompactLabel: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  filterCompactLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  filterCompactClear: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: '#fee2e2',
  },
  filterCompactClearText: {
    color: '#dc2626',
    fontSize: 11,
    fontWeight: '700',
  },
  filterCompactScroll: {
    marginHorizontal: -12,
    paddingHorizontal: 12,
  },
  filterCompactChip: {
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    marginRight: 6,
  },
  filterCompactChipActive: {
    backgroundColor: '#2563eb',
    borderColor: '#2563eb',
  },
  filterCompactChipText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  filterCompactChipTextActive: {
    color: '#ffffff',
  },
  filterCompactCategoryChip: {
    backgroundColor: '#f1f5f9',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    marginRight: 6,
  },
  filterCompactCategoryChipActive: {
    backgroundColor: '#2563eb',
    borderColor: '#2563eb',
  },
  filterCompactCategoryChipText: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  filterCompactCategoryChipTextActive: {
    color: '#ffffff',
  },
  filterCompactResetButton: {
    marginHorizontal: 12,
    marginTop: 8,
    backgroundColor: '#dc2626',
    borderRadius: 8,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  filterCompactResetButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 14,
  },
  itemSeparator: {
    height: 14,
  },
  errorCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 18,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#fee2e2',
  },
  errorTitle: {
    color: '#991b1b',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  error: {
    color: '#b91c1c',
    lineHeight: 20,
    marginBottom: 12,
  },
  retryButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#fee2e2',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  retryButtonText: {
    color: '#b91c1c',
    fontWeight: '700',
  },
  emptyState: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 20,
    alignItems: 'center',
  },
  emptyIcon: {
    marginBottom: 12,
    opacity: 0.5,
  },
  emptyTitle: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
  },
  emptyText: {
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
  },
  categoryFilterRow: {
    marginTop: 12,
  },
  categoryScrollContent: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 0,
  },
  categoryChip: {
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  categoryChipActive: {
    backgroundColor: '#ffffff',
    borderWidth: 2,
    borderColor: '#2563eb',
  },
  categoryChipText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
  },
  categoryChipTextActive: {
    color: '#2563eb',
  },
});
